### PR TITLE
Helloworld example using flask flask and gunicorn

### PR DESCRIPTION
**Pull request by pauldougan**
as a side effect of the recent DCS firebreak (which needed a simple python app to help kickstart the work) I created a super minimal example of deploying a python flask app to GOV.UK PaaS with gunicorn

I propose that we curate a set of similar examples in `helloworld-examples` so that we have a central source for these things. I see this as complementary to the large scale examples in the incubator. 

to review
- [ ] sanity check the text
- [ ] test the example
- [ ] feedback

### CODE REVIEW

**Comment by tlwr** [comment]
The first four or so commits are related to `paas-patterns` which we do not want to include in this PR. Would it be possible to rebase and remove these commits?

**Comment by pauldougan** [comment]
Toby sure   good spot. I'm still chewing over the patterns stuff so I'll leave that out for thr time  being

**Comment by pauldougan** [comment]
Hi @tlwr I ditched the pattern files as suggested

**Comment by tlwr** [comment]
LGTM do you mind if I squash-and-merge to cleanup the git history?

**Comment by pauldougan** [comment]
yes please, you can squash all the history since its of no value

**Pull request merged**
